### ISSUE TITLE
Logout <Button> is misaligned due to react-bootstrap template styling

### ISSUE THREAD

**Issue by Pythonidaer** [Pythonidaer/reddie#7]
This looks like a good first issue to resolve for Bryan, who is already working on this one.

**Comment by Hoffalypse** [comment]
Fixed. not sure if I have the clearance to close issues. Looking now

**Comment by Pythonidaer** [comment]
Way to go @Hoffalypse ! First issue closed. I just added you to the repo/project as a Collaborator, approved your PR to /test/ branch and merged it to /main/ branch. Will close this one out.
